/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'aurora-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./aurora-native.android-arm64.node')
          } else {
            nativeBinding = require('aurora-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'aurora-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./aurora-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('aurora-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'aurora-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./aurora-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('aurora-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'aurora-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./aurora-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('aurora-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'aurora-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./aurora-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('aurora-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'aurora-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./aurora-native.darwin-universal.node')
      } else {
        nativeBinding = require('aurora-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'aurora-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./aurora-native.darwin-x64.node')
          } else {
            nativeBinding = require('aurora-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'aurora-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./aurora-native.darwin-arm64.node')
          } else {
            nativeBinding = require('aurora-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'aurora-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./aurora-native.freebsd-x64.node')
      } else {
        nativeBinding = require('aurora-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'aurora-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./aurora-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('aurora-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'aurora-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./aurora-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('aurora-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'aurora-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./aurora-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('aurora-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'aurora-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./aurora-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('aurora-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'aurora-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./aurora-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('aurora-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'aurora-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./aurora-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('aurora-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'aurora-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./aurora-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('aurora-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'aurora-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./aurora-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('aurora-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'aurora-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./aurora-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('aurora-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { playbackSnapshot, playbackLoad, playbackPlay, playbackPause, playbackSeek, playbackTick, playbackStop, audioBackendCapabilities, nativeAudioStartFile, nativeAudioPlay, nativeAudioPause, nativeAudioSetVolume, nativeAudioSeek, nativeAudioStop, nativeAudioSnapshot, audioDecryptQmc2Chunk, downloadCreate, downloadWrite, downloadCommit, downloadAbort, audioDecryptQmc2File, scanDirectory, parseTrack, readAudioTags, writeAudioTags, scanLyrics, readSettings, writeSettings, settingsRoundtrip, nativeVersion, syncNormalizeBaseUrl, syncValidateSession, providerParseQqTrack, providerParseWyTrack } = nativeBinding

module.exports.playbackSnapshot = playbackSnapshot
module.exports.playbackLoad = playbackLoad
module.exports.playbackPlay = playbackPlay
module.exports.playbackPause = playbackPause
module.exports.playbackSeek = playbackSeek
module.exports.playbackTick = playbackTick
module.exports.playbackStop = playbackStop
module.exports.audioBackendCapabilities = audioBackendCapabilities
module.exports.nativeAudioStartFile = nativeAudioStartFile
module.exports.nativeAudioPlay = nativeAudioPlay
module.exports.nativeAudioPause = nativeAudioPause
module.exports.nativeAudioSetVolume = nativeAudioSetVolume
module.exports.nativeAudioSeek = nativeAudioSeek
module.exports.nativeAudioStop = nativeAudioStop
module.exports.nativeAudioSnapshot = nativeAudioSnapshot
module.exports.audioDecryptQmc2Chunk = audioDecryptQmc2Chunk
module.exports.downloadCreate = downloadCreate
module.exports.downloadWrite = downloadWrite
module.exports.downloadCommit = downloadCommit
module.exports.downloadAbort = downloadAbort
module.exports.audioDecryptQmc2File = audioDecryptQmc2File
module.exports.scanDirectory = scanDirectory
module.exports.parseTrack = parseTrack
module.exports.readAudioTags = readAudioTags
module.exports.writeAudioTags = writeAudioTags
module.exports.scanLyrics = scanLyrics
module.exports.readSettings = readSettings
module.exports.writeSettings = writeSettings
module.exports.settingsRoundtrip = settingsRoundtrip
module.exports.nativeVersion = nativeVersion
module.exports.syncNormalizeBaseUrl = syncNormalizeBaseUrl
module.exports.syncValidateSession = syncValidateSession
module.exports.providerParseQqTrack = providerParseQqTrack
module.exports.providerParseWyTrack = providerParseWyTrack
