/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Preserve the JSON-string API consumed by the Electron bridge and shadow tests. */
export declare function scanDirectory(dir: string): string
export declare function parseTrack(path: string): string
/**
 * Read-only Rust metadata bridge. The JSON envelope is `null` for unsupported
 * extensions and a camelCase partial object for recognized audio files.
 */
export declare function readAudioTags(path: string): string
/**
 * Write the supplied camelCase metadata JSON through the shared Rust tag
 * writer.  The boolean result preserves the core writer's fallback signal
 * for containers whose primary tag type cannot be written by Lofty.
 */
export declare function writeAudioTags(path: string, metadataJson: string): boolean
export declare function scanLyrics(dir: string): string
export declare function readSettings(path: string): string
export declare function settingsRoundtrip(source: string, sandboxPath: string, keyPath: string, newValue: string): string
export declare function nativeVersion(): string
